sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e ci=true docker-react npm run test -- --coverage
